spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=APT_TAX;encrypt=true;trustServerCertificate=true
    username: sa
    password: Star8903!@

server:
  port: 8086
